# -*- coding: utf-8 -*-
query = "Analyze THBS2's dual functions in tumor immunity: immunosuppressive mechanisms, correlation with checkpoint inhibitor responses, and biomarker potential."

plan = {
    "thought": "After analyzing the current logical chain, I identified that the step query for the 'Consequence' step is too specific and restrictive, which is likely why no relevant papers were found. The query 'THBS2 AND immunosuppression AND mechanism AND signaling AND tumor' combines too many specific terms, especially 'immunosuppression' which may be too narrow. THBS2 may have immune modulatory effects that aren't strictly classified as 'immunosuppression' in the literature. Additionally, requiring both 'mechanism' AND 'signaling' is redundant and overly limiting. I'll modify this query to be more inclusive while maintaining the intent of exploring THBS2's molecular mechanisms in immune regulation within tumors. The remaining logical chain is sound and follows a rational progression from basic characteristics to clinical applications, so I'll keep the other steps unchanged.",
    "Logical_chain": "This logical chain explores THBS2's dual functions in tumor immunity by first establishing its expression patterns in tumors, understanding its basic structure and functions, examining its interactions with immune cells, identifying its molecular mechanisms in immune modulation, exploring its relationship with checkpoint molecules, assessing its correlation with immunotherapy responses, and finally evaluating its potential as a biomarker.",
    "steps": [
        {
            "relationship": "Starting point",
            "purpose": "To establish the presence and expression patterns of THBS2 in various tumor microenvironments",
            "Verification_Point": "Expression levels and patterns of THBS2 in different cancer types and their tumor microenvironments",
            "Step_query": "THBS2 AND tumor microenvironment AND expression AND cancer"
        },
        {
            "relationship": "Foundation",
            "purpose": "To understand the structural characteristics and basic biological functions of THBS2 that may relate to its immune functions",
            "Verification_Point": "Molecular structure and fundamental biological functions of THBS2 with potential relevance to immune regulation",
            "Step_query": "THBS2 AND structure AND function AND immune"
        },
        {
            "relationship": "Mechanism",
            "purpose": "To identify how THBS2 interacts with various immune cell populations in the tumor microenvironment",
            "Verification_Point": "Direct and indirect interactions between THBS2 and immune cells (T cells, macrophages, dendritic cells, etc.)",
            "Step_query": "THBS2 AND (T cells OR macrophages OR dendritic cells OR NK cells) AND tumor"
        },
        {
            "relationship": "Consequence",
            "purpose": "To elucidate the specific molecular mechanisms by which THBS2 contributes to immunosuppression in tumors",
            "Verification_Point": "Molecular pathways and signaling mechanisms through which THBS2 mediates immunosuppressive effects",
            "Step_query": "THBS2 AND (immune regulation OR immune modulation OR immunosuppression) AND (signaling OR pathway) AND tumor"
        },
        {
            "relationship": "Association",
            "purpose": "To explore the relationship between THBS2 and known immune checkpoint molecules (PD-1/PD-L1, CTLA-4, etc.)",
            "Verification_Point": "Interactions or correlations between THBS2 expression and immune checkpoint molecules",
            "Step_query": "THBS2 AND (PD-1 OR PD-L1 OR CTLA-4 OR immune checkpoint) AND interaction"
        },
        {
            "relationship": "Clinical correlation",
            "purpose": "To assess how THBS2 levels correlate with responses to checkpoint inhibitor therapies across cancer types",
            "Verification_Point": "Association between THBS2 expression and clinical outcomes in patients treated with immune checkpoint inhibitors",
            "Step_query": "THBS2 AND (checkpoint inhibitor OR immunotherapy) AND (response OR outcome OR efficacy)"
        },
        {
            "relationship": "Application",
            "purpose": "To evaluate the potential of THBS2 as a biomarker for predicting immunotherapy response or stratifying patients",
            "Verification_Point": "Evidence supporting or refuting THBS2's utility as a predictive or prognostic biomarker for immunotherapy",
            "Step_query": "THBS2 AND biomarker AND (immunotherapy OR checkpoint inhibitor) AND prediction"
        }
    ]
}

paper = [{'biorxiv': [], 'medrxiv': [], 'pubmed': [{
    'Title': 'Integrating single-cell and bulk RNA sequencing data unveils antigen presentation and process-related CAFS and establishes a predictive signature in prostate cancer.',
    'Abstract': 'Cancer-associated fibroblasts (CAFs) are heterogeneous and can influence the progression of prostate cancer in multiple ways; however, their capacity to present and process antigens in PRAD has not been investigated. In this study, antigen presentation and process-related CAFs (APPCAFs) were identified using bioinformatics, and the clinical implications of APPCAF-related signatures in PRAD were investigated.',
    'PMID': '38221616', 'DOI': '10.1186/s12967-023-04807-y',
    'Journal_Title': 'Journal of translational medicine',
    'ISO_Abbreviation': 'J Transl Med', 'Journal_Score': '8.125',
    'ISSN': '1479-5876', 'ArticleDate': '2024-01-14',
    'URL': 'https://pubmed.ncbi.nlm.nih.gov/38221616/', 'Level': 2},
    {
        'Title': 'Tumor-stroma TGF-β1-THBS2 feedback circuit drives pancreatic ductal adenocarcinoma progression via integrin α<sub>v</sub>β<sub>3</sub>/CD36-mediated activation of the MAPK pathway.',
        'Abstract': 'The pancreatic ductal adenocarcinoma (PDAC) microenvironment contains dense desmoplastic stroma dominated by cancer-associated fibroblasts (CAFs) and is crucial to cancer development and progression. Several studies have revealed that thrombospondin 2 (THBS2) is a valuable serological-marker in PDAC. However, the detailed mechanism of the cancer-stroma interactome remains unclear. Here we showed that elevated THBS2 expression in PDAC was predominantly restricted to stroma and correlated with tumor progression and poor prognosis by quantitative proteomics and immunohistochemistry analyses. RNA in situ hybridization confirmed that CAFs but not neoplastic cells expressed THBS2 in precancerous lesions and its levels gradually increased with disease progression in genetically engineered mouse models. Mechanistically, cancer cell-secreted TGF-β1 activated CAFs to induce THBS2 expression via the p-Smad2/3 pathway. Consequently, CAF-derived THBS2 bound to the membrane receptors integrin α<sub>v</sub>β<sub>3</sub>/CD36 and activated the MAPK pathway in PDAC cells to promote tumor growth and adhesion in vitro and in vivo. Inhibition of integrin α<sub>v</sub>β<sub>3</sub>, CD36, MEK and JNK rescued THBS2-induced malignant phenotypes. In conclusion, the TGF-β1-THBS2-integrin α<sub>v</sub>β<sub>3</sub>/CD36-MAPK cascade forms a complex feedback circuit to mediate reciprocal interactions of pancreatic cancer cells-CAFs. THBS2 may act as a novel therapeutic-target to block the cancer-stroma communication.',
        'PMID': '34958892', 'DOI': 'S0304-3835(21)00642-X',
        'Journal_Title': 'Cancer letters',
        'ISO_Abbreviation': 'Cancer Lett',
        'Journal_Score': '10.8666666666667', 'ISSN': '1872-7980',
        'ArticleDate': '2021-12-24',
        'URL': 'https://pubmed.ncbi.nlm.nih.gov/34958892/', 'Level': 1},
    {
        'Title': 'Single-cell and bulk RNA sequencing reveal ligands and receptors associated with worse overall survival in serous ovarian cancer.',
        'Abstract': 'Serous ovarian carcinoma is the most frequent histological subgroup of ovarian cancer and the leading cause of death among gynecologic tumors. The tumor microenvironment and cancer-associated fibroblasts (CAFs) have a critical role in the origin and progression of cancer. We comprehensively characterized the crosstalk between CAFs and ovarian cancer cells from malignant fluids to identify specific ligands and receptors mediating intercellular communications and disrupted pathways related to prognosis and therapy response.',
        'PMID': '36352420', 'DOI': '10.1186/s12964-022-00991-4',
        'Journal_Title': 'Cell communication and signaling : CCS',
        'ISO_Abbreviation': 'Cell Commun Signal',
        'Journal_Score': '6.58064516129032', 'ISSN': '1478-811X',
        'ArticleDate': '2022-11-09',
        'URL': 'https://pubmed.ncbi.nlm.nih.gov/36352420/', 'Level': 2},
    {
        'Title': 'The RP11-417E7.1/THBS2 signaling pathway promotes colorectal cancer metastasis by activating the Wnt/β-catenin pathway and facilitating exosome-mediated M2 macrophage polarization.',
        'Abstract': 'Metastasis is the major cause of colorectal cancer (CRC) mortality. Emerging evidence suggests that long noncoding RNAs (lncRNAs) drive cancer metastasis and that their regulatory pathways could be targeted for preventing metastasis. However, the underlying mechanisms of lncRNAs in CRC metastasis remain poorly understood.',
        'PMID': '39020380', 'DOI': '10.1186/s13046-024-03107-7',
        'Journal_Title': 'Journal of experimental & clinical cancer research : CR',
        'ISO_Abbreviation': 'J Exp Clin Cancer Res',
        'Journal_Score': '14.8181818181818', 'ISSN': '1756-9966',
        'ArticleDate': '2024-07-17',
        'URL': 'https://pubmed.ncbi.nlm.nih.gov/39020380/', 'Level': 1},
    {
        'Title': 'Multi-scale integrative analyses identify THBS2<sup>+</sup> cancer-associated fibroblasts as a key orchestrator promoting aggressiveness in early-stage lung adenocarcinoma.',
        'Abstract': '<b>Rationale:</b> Subsets of patients with early-stage lung adenocarcinoma (LUAD) have a poor post-surgical course after curative surgery. However, biomarkers stratifying this high-risk subset and molecular underpinnings underlying the aggressive phenotype remain unclear. <b>Methods:</b> We integrated bulk and single-cell transcriptomics, proteomics, secretome and spatial profiling of clinical early-stage LUAD samples to identify molecular underpinnings that promote the aggressive phenotype. <b>Results:</b> We identified and validated THBS2, at multi-omic levels, as a tumor size-independent biomarker that robustly predicted post-surgical survival in multiple independent clinical cohorts of early-stage LUAD. Furthermore, scRNA-seq data revealed that THBS2 is exclusively derived from a specific cancer-associated fibroblast (CAF) subset that is distinct from CAFs defined by classical markers. Interestingly, our data demonstrated that THBS2 was preferentially secreted via exosomes in early-stage LUAD tumors with high aggressiveness, and its levels in the peripheral plasma associated with short recurrence-free survival. Further characterization showed that THBS2-high early-stage LUAD was characterized by suppressed antitumor immunity. Specifically, beyond tumor cells, THBS2+ CAFs mainly interact with B and CD8+ T lymphocytes as well as macrophages within tumor microenvironment of early-stage LUAD, and THBS2-high LUAD was associated with decreased immune cell infiltrates but increased immune exhaustion marker. Clinically, high THBS2 expression predicted poor response to immunotherapies and short post-treatment survival of patients. Finally, THBS2 recombinant protein suppressed <i>ex vivo</i> T cells proliferation and promoted <i>in vivo</i> LUAD tumor growth and distant micro-metastasis. <b>Conclusions:</b> Our multi-level analyses uncovered tumor-specific THBS2+ CAFs as a key orchestrator promoting aggressiveness in early-stage LUAD.',
        'PMID': '35547750', 'DOI': '10.7150/thno.69590',
        'Journal_Title': 'Theranostics',
        'ISO_Abbreviation': 'Theranostics',
        'Journal_Score': '27.8571428571429', 'ISSN': '1838-7640',
        'ArticleDate': '2022-03-28',
        'URL': 'https://pubmed.ncbi.nlm.nih.gov/35547750/', 'Level': 1},
    {
        'Title': 'Proteomic profiling of tumor microenvironment and prognosis risk prediction in stage I lung adenocarcinoma.',
        'Abstract': 'With the increasing popularity of CT screening, more cases of early-stage lung cancer are being diagnosed. However, 24.5% of stage I non-small-cell lung cancer (NSCLC) patients still experience treatment failure post-surgery. Biomarkers to predict lung cancer patients at high risk of recurrence are needed.',
        'PMID': '38621342', 'DOI': 'S0169-5002(24)00099-0',
        'Journal_Title': 'Lung cancer (Amsterdam, Netherlands)',
        'ISO_Abbreviation': 'Lung Cancer',
        'Journal_Score': '5.68421052631579', 'ISSN': '1872-8332',
        'ArticleDate': '2024-04-12',
        'URL': 'https://pubmed.ncbi.nlm.nih.gov/38621342/', 'Level': 2},
    {
        'Title': 'Detection of lymph node metastasis in colon cancer by ectopically expressed fibroblast markers FOXQ1 and THBS2.',
        'Abstract': 'Approximately 25% of colon cancer (CC) patients having curative surgery will relapse. Therefore, it is crucial to identify patients with increased recurrence risk to offer them adjuvant chemotherapy. Three markers with prominent expression in fibroblasts: forkhead box Q1 (FOXQ1), matrix metalloproteinase-11 (MMP11), and thrombospondin-2 (THBS2), and the fibroblast expressed chemokine CXCL12 were selected for studies because of the critical role of fibroblasts in the microenvironment of the tumor.',
        'PMID': '38156105', 'DOI': '10.3389/fonc.2023.1297324',
        'Journal_Title': 'Frontiers in oncology',
        'ISO_Abbreviation': 'Front Oncol',
        'Journal_Score': '2.65040650406504', 'ISSN': '2234-943X',
        'ArticleDate': '2023-12-14',
        'URL': 'https://pubmed.ncbi.nlm.nih.gov/38156105/', 'Level': 1},
    {
        'Title': 'Single-cell RNA sequencing and cell-cell communication analysis reveal tumor microenvironment associated with chemotherapy responsiveness in ovarian cancer.',
        'Abstract': 'To investigate the impact of the tumor microenvironment (TME) on the responsiveness to chemotherapy in ovarian cancer (OV).',
        'PMID': '39122983', 'DOI': '10.1007/s12094-024-03655-6',
        'Journal_Title': 'Clinical & translational oncology : official publication of the Federation of Spanish Oncology Societies and of the National Cancer Institute of Mexico',
        'ISO_Abbreviation': 'Clin Transl Oncol',
        'Journal_Score': '1.73404255319149', 'ISSN': '1699-3055',
        'ArticleDate': '2024-08-09',
        'URL': 'https://pubmed.ncbi.nlm.nih.gov/39122983/', 'Level': 2},
    {
        'Title': 'Identification of a basement membrane gene signature for predicting prognosis and estimating the tumor immune microenvironment in prostate cancer.',
        'Abstract': 'Basement membrane plays an important role in tumor invasion and metastasis, which is closely related to prognosis. However, the prognostic value and biology of basement membrane genes (BMGs) in prostate cancer (PCa) remain unknown. In the TCGA training set, we used differentially expressed gene analysis, protein-protein interaction networks, univariate and multivariate Cox regression, and least absolute shrinkage and selection operator regression to construct a basement membrane-related risk model (BMRM) and validated its effectiveness in the MSKCC validation set. Furthermore, the accurate nomogram was constructed to improve clinical applicability. Patients with PCa were divided into high-risk and low-risk groups according to the optimal cut-off value of the basement membrane-related risk score (BMRS). It was found that BMRS was significantly associated with RFS, T-stage, Gleason score, and tumor microenvironmental characteristics in PCa patients. Further analysis showed that the model grouping was closely related to tumor immune microenvironment characteristics, immune checkpoint inhibitors, and chemotherapeutic drug sensitivity. In this study, we developed a new BMGs-based prognostic model to determine the prognostic value of BMGs in PCa. Finally, we confirmed that THBS2, a key gene in BMRM, may be an important link in the occurrence and progression of PCa. This study provides a novel perspective to assess the prognosis of PCa patients and provides clues for the selection of future personalized treatment regimens.',
        'PMID': '38240702', 'DOI': '10.18632/aging.205445',
        'Journal_Title': 'Aging',
        'ISO_Abbreviation': 'Aging (Albany NY)', 'Journal_Score': 'None',
        'ISSN': '1945-4589', 'ArticleDate': '2024-01-17',
        'URL': 'https://pubmed.ncbi.nlm.nih.gov/38240702/', 'Level': 1},
    {
        'Title': 'Identification of Key Genes Associated with Tumor Microenvironment Infiltration and Survival in Gastric Adenocarcinoma via Bioinformatics Analysis.',
        'Abstract': 'Gastric carcinoma (GC) is the fifth most commonly diagnosed cancer and the third leading cause of cancer-related deaths globally. The tumor microenvironment plays a significant role in the pathogenesis, prognosis, and response to immunotherapy. However, the immune-related molecular mechanisms underlying GC remain elusive. Bioinformatics analysis of the gene expression of GC and paracancerous healthy tissues from the same patient was performed to identify the key genes and signaling pathways, as well as their correlation to the infiltration of the tumor microenvironment (TME) by various immune cells related to GC development.',
        'PMID': '38610959', 'DOI': '10.3390/cancers16071280',
        'Journal_Title': 'Cancers',
        'ISO_Abbreviation': 'Cancers (Basel)',
        'Journal_Score': '3.83529411764706', 'ISSN': '2072-6694',
        'ArticleDate': '2024-03-26',
        'URL': 'https://pubmed.ncbi.nlm.nih.gov/38610959/',
        'Level': 2}]}, {'biorxiv': [], 'medrxiv': [], 'pubmed': [
    {'Title': 'Prognostic and Immunological Role of THBS2 in Colorectal cancer.',
     'Abstract': 'Thrombospondin 2 (THBS2) acts as oncogenic or tumor suppressive gene in diverse cancers. Here we studied the prognostic and immunological role of THBS2 in colorectal cancer (CRC) using bioinformatic analysis.',
     'PMID': '34471634', 'DOI': '10.1155/2021/1124985', 'Journal_Title': 'BioMed research international',
     'ISO_Abbreviation': 'Biomed Res Int', 'Journal_Score': '1.82242990654206', 'ISSN': '2314-6141',
     'ArticleDate': '2021-08-21', 'URL': 'https://pubmed.ncbi.nlm.nih.gov/34471634/', 'Level': 1}, {
        'Title': 'Mining the Plasma Proteome for Insights into the Molecular Pathology of Pulmonary Arterial Hypertension.',
        'Abstract': '<b>Rationale:</b> Pulmonary arterial hypertension (PAH) is characterized by structural remodeling of pulmonary arteries and arterioles. Underlying biological processes are likely reflected in a perturbation of circulating proteins. <b>Objectives:</b> To quantify and analyze the plasma proteome of patients with PAH using inherited genetic variation to inform on underlying molecular drivers. <b>Methods:</b> An aptamer-based assay was used to measure plasma proteins in 357 patients with idiopathic or heritable PAH, 103 healthy volunteers, and 23 relatives of patients with PAH. In discovery and replication subgroups, the plasma proteomes of PAH and healthy individuals were compared, and the relationship to transplantation-free survival in PAH was determined. To examine causal relationships to PAH, protein quantitative trait loci (pQTL) that influenced protein levels in the patient population were used as instruments for Mendelian randomization (MR) analysis. <b>Measurements and Main Results:</b> From 4,152 annotated plasma proteins, levels of 208 differed between patients with PAH and healthy subjects, and 49 predicted long-term survival. MR based on <i>cis</i>-pQTL located in proximity to the encoding gene for proteins that were prognostic and distinguished PAH from health estimated an adverse effect for higher levels of netrin-4 (odds ratio [OR], 1.55; 95% confidence interval [CI], 1.16-2.08) and a protective effect for higher levels of thrombospondin-2 (OR, 0.83; 95% CI, 0.74-0.94) on PAH. Both proteins tracked the development of PAH in previously healthy relatives and changes in thrombospondin-2 associated with pulmonary arterial pressure at disease onset. <b>Conclusions:</b> Integrated analysis of the plasma proteome and genome implicates two secreted matrix-binding proteins, netrin-4 and thrombospondin-2, in the pathobiology of PAH.',
        'PMID': '35394406', 'DOI': '10.1164/rccm.202109-2106OC',
        'Journal_Title': 'American journal of respiratory and critical care medicine',
        'ISO_Abbreviation': 'Am J Respir Crit Care Med', 'Journal_Score': '27.0', 'ISSN': '1535-4970',
        'ArticleDate': '2022-06-15', 'URL': 'https://pubmed.ncbi.nlm.nih.gov/35394406/', 'Level': 2},
    {'Title': 'Gene Expression Network Analysis of Precursor Lesions in Familial Pancreatic Cancer.',
     'Abstract': '<b>Purpose:</b> High-grade pancreatic intraepithelial neoplasia (PanIN) are aggressive premalignant lesions, associated with risk of progression to pancreatic ductal adenocarcinoma (PDAC). A depiction of co-dysregulated gene activity in high-grade familial pancreatic cancer (FPC)-related PanIN lesions may characterize the molecular events during the progression from familial PanIN to PDAC. <b>Materials and Methods:</b> We performed weighted gene coexpression network analysis (WGCNA) to identify clusters of coexpressed genes associated with FPC-related PanIN lesions in 13 samples with PanIN-2/3 from FPC predisposed individuals, 6 samples with PDAC from sporadic pancreatic cancer (SPC) patients, and 4 samples of normal donor pancreatic tissue. <b>Results:</b> WGCNA identified seven differentially expressed gene (DEG) modules and two commonly expressed gene (CEG) modules with significant enrichment for Gene Ontology (GO) terms in FPC and SPC, including three upregulated (<i>p</i>\u2009<\u20095e-05) and four downregulated (<i>p</i>\u2009<\u20096e-04) gene modules in FPC compared to SPC. Among the DEG modules, the upregulated modules include 14 significant genes (<i>p</i>\u2009<\u20091e-06): <i>ALOX12-AS1</i>, <i>BCL2L11</i>, <i>EHD4</i>, <i>C4B</i>, <i>BTN3A3</i>, <i>NDUFA11</i>, <i>RBM4B</i>, <i>MYOC</i>, <i>ZBTB47</i>, <i>TTTY15</i>, <i>NAPRT</i>, <i>LOC102606465</i>, <i>LOC100505711</i>, and <i>PTK2</i>. The downregulated modules include 170 genes (<i>p</i>\u2009<\u20091e-06), among them 13 highly significant genes (<i>p</i>\u2009<\u20091e-10): <i>COL10A1</i>, <i>SAMD9</i>, <i>PLPP4</i>, <i>COMP</i>, <i>POSTN</i>, <i>IGHV4-31</i>, <i>THBS2</i>, <i>MMP9</i>, <i>FNDC1</i>, <i>HOPX</i>, <i>TMEM200A</i>, <i>INHBA</i>, and <i>SULF1</i>. The DEG modules are enriched for GO terms related to mitochondrial structure and adenosine triphosphate metabolic processes, extracellular structure and binding properties, humoral and complement mediated immune response, ligand-gated ion channel activity, and transmembrane receptor activity. Among the CEG modules, <i>IL22RA1</i>, <i>DPEP1</i>, and <i>BCAT1</i> were found as highly connective hub genes associated with both FPC and SPC. <b>Conclusion:</b> FPC-related PanIN lesions exhibit a common molecular basis with SPC as shown by gene network activities and commonly expressed high-connectivity hub genes. The differential molecular pathology of FPC and SPC involves multiple coexpressed gene clusters enriched for GO terms including extracellular activities and mitochondrion function.',
     'PMID': '32783019', 'DOI': '10.1089/pancan.2020.0007', 'Journal_Title': 'Journal of pancreatic cancer',
     'ISO_Abbreviation': 'J Pancreat Cancer', 'Journal_Score': 'None', 'ISSN': '2475-3246', 'ArticleDate': '2020-08-05',
     'URL': 'https://pubmed.ncbi.nlm.nih.gov/32783019/', 'Level': 2}, {
        'Title': 'Matricellular protein thrombospondins: influence on ocular angiogenesis, wound healing and immuneregulation.',
        'Abstract': 'Thrombospondins are a family of large multi-domain glycoproteins described as matricelluar proteins based on their ability to interact with a broad range of receptors, matrix molecules, growth factors or proteases, and to modulate array of cellular functions including intracellular signaling, proliferation and migration. Two members of the thrombospondin family, thrombospondin 1 (TSP-1) and thrombospondin 2 (TSP-2) are studied extensively to determine their structure and function. While expressed at low levels in normal adult tissues, their increased expression is seen predominantly in response to cellular perturbations. Despite structural similarities, a notable functional difference between TSP-1 and TSP-2 includes the ability of former to activate of latent TGF-β and its competitive inhibition by the latter. Both these thrombospondins are reported to play important roles in TGF-β rich ocular environment with most reports related to TSP-1. They are expressed by many ocular cell types and detectable in the aqueous and vitreous humor. TSP-1 and TSP-2 influence many cellular interactions in the eye such as angiogenesis, cell migration, wound healing, TGF-β activation and regulation of inflammatory immune responses. Together, these processes are known to contribute to the immune privilege status of the eye. Emerging roles of TSP-1 and TSP-2 in ocular functions and pathology are reviewed here.',
        'PMID': '24559320', 'DOI': '10.3109/02713683.2013.877936', 'Journal_Title': 'Current eye research',
        'ISO_Abbreviation': 'Curr Eye Res', 'Journal_Score': '2.22727272727273', 'ISSN': '1460-2202',
        'ArticleDate': '2014-02-21', 'URL': 'https://pubmed.ncbi.nlm.nih.gov/24559320/', 'Level': 1},
    {'Title': 'Current evidence for a modulation of low back pain by human genetic variants.',
     'Abstract': 'The manifestation of chronic back pain depends on structural, psychosocial, occupational and genetic influences. Heritability estimates for back pain range from 30% to 45%. Genetic influences are caused by genes affecting intervertebral disc degeneration or the immune response and genes involved in pain perception, signalling and psychological processing. This inter-individual variability which is partly due to genetic differences would require an individualized pain management to prevent the transition from acute to chronic back pain or improve the outcome. The genetic profile may help to define patients at high risk for chronic pain. We summarize genetic factors that (i) impact on intervertebral disc stability, namely Collagen IX, COL9A3, COL11A1, COL11A2, COL1A1, aggrecan (AGAN), cartilage intermediate layer protein, vitamin D receptor, metalloproteinsase-3 (MMP3), MMP9, and thrombospondin-2, (ii) modify inflammation, namely interleukin-1 (IL-1) locus genes and IL-6 and (iii) and pain signalling namely guanine triphosphate (GTP) cyclohydrolase 1, catechol-O-methyltransferase, mu opioid receptor (OPMR1), melanocortin 1 receptor (MC1R), transient receptor potential channel A1 and fatty acid amide hydrolase and analgesic drug metabolism (cytochrome P450 [CYP]2D6, CYP2C9).',
     'PMID': '19228264', 'DOI': '10.1111/j.1582-4934.2009.00703.x',
     'Journal_Title': 'Journal of cellular and molecular medicine', 'ISO_Abbreviation': 'J Cell Mol Med',
     'Journal_Score': '3.48214285714286', 'ISSN': '1582-4934', 'ArticleDate': '2009-02-17',
     'URL': 'https://pubmed.ncbi.nlm.nih.gov/19228264/', 'Level': 2}, {
        'Title': 'Integrated metabolome and transcriptome analysis reveals key genes and pathways associated with egg yolk percentage in chicken.',
        'Abstract': 'Yolk percentage is a critical index in the egg product industry, reflecting both nutritional value and economic benefits. To elucidate the underlying mechanisms that contribute to variations in egg yolk percentage, we performed integrated transcriptome and metabolome analyses on the liver, ovary, and magnum tissues of Rhode Island Red chickens with high and low yolk percentages. A total of 322 differentially expressed genes (DEGs) and 128 significantly differential metabolites (SDMs) (VIP>1, P < 0.05) were identified in the liver, whereas 419 DEGs and 215 SDMs were detected in the ovary, and 238 DEGs along with 47 SDMs were found in the magnum. In the liver, genes such as HMGCR, DHCR7, MSMO1, and CYP7A1 were linked to cholesterol metabolism, essential for steroid hormone synthesis and yolk formation, while ACACB, ACSL1, ACSL4, LPL, and SGPP2 were involved in fatty acid biosynthesis, a key process for supplying energy and structural components of the yolk. In the ovary, COL6A6, COMP, CHAD, ITGA7, THBS2, and TNC contributed to extracellular matrix-receptor interactions, which are fundamental for follicle development and oocyte maturation. In the magnum, UGT1A1, MAOB, and ALDH3B2 participated in drug metabolism-cytochrome P450 and amino acid metabolism, ensuring a proper environment for egg white formation and potentially influencing nutrient allocation to the yolk. Metabolic pathway enrichment revealed that steroid hormone biosynthesis, glycerophospholipid metabolism, and betaine metabolism were predominant in the liver; pyruvate, taurine, and hypotaurine metabolism in the ovary; and phenylalanine metabolism in the magnum. Moreover, integrated analysis highlighted key metabolites and genes potentially regulating yolk deposition, including 7,8-dihydroneopterin and Pg 38:4 in the liver (related to immune modulation and lipid metabolism, respectively), thalsimine in the ovary, as well as DL-glutamine in the magnum, all of which may be crucial for maintaining metabolic homeostasis and supporting egg formation. Collectively, these findings deepen our understanding of how distinct molecular and metabolic pathways in the liver, ovary, and magnum orchestrate yolk proportion and deposition. Such insights may advance future strategies to improve egg quality and productivity in poultry breeding programs.',
        'PMID': '39914020', 'DOI': 'S0032-5791(25)00052-5', 'Journal_Title': 'Poultry science',
        'ISO_Abbreviation': 'Poult Sci', 'Journal_Score': '17.2', 'ISSN': '1525-3171', 'ArticleDate': '2025-01-17',
        'URL': 'https://pubmed.ncbi.nlm.nih.gov/39914020/', 'Level': 2}, {
        'Title': 'mRNA Expression of thrombospondin 1, 2 and 3 from proximal to distal in human abdominal aortic aneurysm - preliminary report.',
        'Abstract': "Abdominal aortic aneurysm is a process involving the disruption and reconstruction of the extracellular matrix and the apoptosis of smooth muscle cells under the strong influence of the immune system. Thrombospondins are proteins that influence a wide range of cell-matrix interactions. While THBS1 and THBS2 are widely studied, the effects of THBS3 on extracellular matrix and vascular cells are poorly understood. Additionally, it is not known whether expression of these genes' changes along the aneurysm tissue. Here we analyzed the expression of THBSs mRNA isolated from the harvested tissues along the aneurysm divided into three zones based on their morphology. Total mRNA was isolated from 13 male patients undergoing scheduled open aortic repair, with each aneurysm divided into a proximal part, an aneurysm bag, and a distal part with border tissue as a control. Two step real-time PCR analysis with random hexamers was performed, which allowed the detection of significantly increased expression of all analyzed thrombospondins, especially THBS3, at the control tissue. Overexpression of THBSs may have a destabilizing effect on the structure of the extracellular matrix by affecting both the matrix producing cells and by inhibiting the activity of matrix proteins.",
        'PMID': '34669362', 'DOI': '10.18388/abp.2020_5645', 'Journal_Title': 'Acta biochimica Polonica',
        'ISO_Abbreviation': 'Acta Biochim Pol', 'Journal_Score': '1.17712177121771', 'ISSN': '1734-154X',
        'ArticleDate': '2021-10-20', 'URL': 'https://pubmed.ncbi.nlm.nih.gov/34669362/', 'Level': 2}]},
         {'biorxiv': [], 'medrxiv': [], 'pubmed': [{
             'Title': 'CAF-macrophage crosstalk in tumour microenvironments governs the response to immune checkpoint blockade in gastric cancer peritoneal metastases.',
             'Abstract': 'Peritoneal metastasis is the most common metastasis pattern of gastric cancer. Patients with gastric cancer peritoneal metastasis (GCPM) have a poor prognosis and respond poorly to conventional treatments. Recently, immune checkpoint blockade (ICB) has demonstrated favourable efficacy in the treatment of GCPM. Stratification of best responders and elucidation of resistance mechanisms of ICB therapies are highly important and remain major clinical challenges.',
             'PMID': '39537239', 'DOI': '10.1136/gutjnl-2024-333617',
             'Journal_Title': 'Gut', 'ISO_Abbreviation': 'Gut',
             'Journal_Score': '36.75', 'ISSN': '1468-3288',
             'ArticleDate': '2025-02-06',
             'URL': 'https://pubmed.ncbi.nlm.nih.gov/39537239/', 'Level': 1},
             {
                 'Title': 'Integrating single-cell and bulk RNA sequencing data unveils antigen presentation and process-related CAFS and establishes a predictive signature in prostate cancer.',
                 'Abstract': 'Cancer-associated fibroblasts (CAFs) are heterogeneous and can influence the progression of prostate cancer in multiple ways; however, their capacity to present and process antigens in PRAD has not been investigated. In this study, antigen presentation and process-related CAFs (APPCAFs) were identified using bioinformatics, and the clinical implications of APPCAF-related signatures in PRAD were investigated.',
                 'PMID': '38221616', 'DOI': '10.1186/s12967-023-04807-y',
                 'Journal_Title': 'Journal of translational medicine',
                 'ISO_Abbreviation': 'J Transl Med', 'Journal_Score': '8.125',
                 'ISSN': '1479-5876', 'ArticleDate': '2024-01-14',
                 'URL': 'https://pubmed.ncbi.nlm.nih.gov/38221616/', 'Level': 2},
             {
                 'Title': 'XBP1 regulates the protumoral function of tumor-associated macrophages in human colorectal cancer.',
                 'Abstract': 'Macrophages are among the most abundant immune cells in colorectal cancer (CRC). Re-educating tumor-associated macrophages (TAMs) to switch from protumoral to anti-tumoral activity is an attractive treatment strategy that warrants further investigation. However, little is known about the key pathway that is activated in TAMs. In this study, infitrating CD206<sup>+</sup> TAMs in CRC were sorted and subjected to RNA-seq analysis. Differentially expressed genes were found to be enriched in unfolded protein response/endoplasmic reticulum stress response processes, and XBP1 splicing/activation was specifically observed in TAMs. XBP1 activation in TAMs promoted the growth and metastasis of CRC. Ablation of XBP1 inhibited the expression of the pro-tumor cytokine signature of TAMs, including IL-6, VEGFA, and IL-4. Simultaneously, XBP1 depletion could directly inhibit the expression of SIRPα and THBS1, thereby blocking "don\'t eat me" recognition signals and enhancing phagocytosis. Therapeutic XBP1 gene editing using AAV2-sgXBP1 enhanced the anti-tumor activity. Together, XBP1 activation in TAMs drives CRC progression by elevating pro-tumor cytokine expression and secretion, as well as inhibiting macrophage phagocytosis. Targeting XBP1 signaling in TAMs may be a potential strategy for CRC therapy.',
                 'PMID': '34667145', 'DOI': '10.1038/s41392-021-00761-7',
                 'Journal_Title': 'Signal transduction and targeted therapy',
                 'ISO_Abbreviation': 'Signal Transduct Target Ther',
                 'Journal_Score': '319.0', 'ISSN': '2059-3635',
                 'ArticleDate': '2021-10-20',
                 'URL': 'https://pubmed.ncbi.nlm.nih.gov/34667145/', 'Level': 1},
             {
                 'Title': 'The RP11-417E7.1/THBS2 signaling pathway promotes colorectal cancer metastasis by activating the Wnt/β-catenin pathway and facilitating exosome-mediated M2 macrophage polarization.',
                 'Abstract': 'Metastasis is the major cause of colorectal cancer (CRC) mortality. Emerging evidence suggests that long noncoding RNAs (lncRNAs) drive cancer metastasis and that their regulatory pathways could be targeted for preventing metastasis. However, the underlying mechanisms of lncRNAs in CRC metastasis remain poorly understood.',
                 'PMID': '39020380', 'DOI': '10.1186/s13046-024-03107-7',
                 'Journal_Title': 'Journal of experimental & clinical cancer research : CR',
                 'ISO_Abbreviation': 'J Exp Clin Cancer Res',
                 'Journal_Score': '14.8181818181818', 'ISSN': '1756-9966',
                 'ArticleDate': '2024-07-17',
                 'URL': 'https://pubmed.ncbi.nlm.nih.gov/39020380/', 'Level': 1},
             {
                 'Title': 'Systematic analysis of integrated bioinformatics to identify upregulated THBS2 expression in colorectal cancer cells inhibiting tumour immunity through the HIF1A/Lactic Acid/GPR132 pathway.',
                 'Abstract': 'THBS2, a member of the extracellular matrix glycoprotein family, can effectively inhibit tumour growth and angiogenesis. This study aimed to investigate the biological role of THBS2 in various types of cancers and the mechanisms underlying the malignant progression of colorectal cancer (CRC).',
                 'PMID': '37884956', 'DOI': '10.1186/s12935-023-03103-5',
                 'Journal_Title': 'Cancer cell international',
                 'ISO_Abbreviation': 'Cancer Cell Int',
                 'Journal_Score': '5.92727272727273', 'ISSN': '1475-2867',
                 'ArticleDate': '2023-10-27',
                 'URL': 'https://pubmed.ncbi.nlm.nih.gov/37884956/', 'Level': 1},
             {
                 'Title': 'THBS2 is Closely Related to the Poor Prognosis and Immune Cell Infiltration of Gastric Cancer.',
                 'Abstract': '<b>Background:</b> The potential functions of Thrombospondin 2 (THBS2) in the progression and immune infiltration of gastric cancer (GC) remain unclear. The purpose of this study was to clarify the role of THBS2 in GC prognosis and the relationship between THBS2 and GC immune cell infiltration. <b>Material and Methods:</b> The differential expression levels of THBS2 in the GC and cancer-adjacent tissues were identified using the TCGA databases and verified using real-time polymerase chain reaction (PCR), immunohistochemical staining and two datasets from Gene Expression Omnibus (GEO). THBS2 related differential expressed genes (DEGs) were identified and used for further functional enrichment analysis and Gene Set Enrichment Analysis (GSEA). Furthermore, a THBS2-related immune infiltration analysis was also performed. Kaplan-Meier and Cox regression analyses were utilized to illustrate the effects of THBS2 on the prognosis and clinical variables of GC. Finally, a nomogram was constructed to predict the survival probability of patients with GC. <b>Results:</b> The THBS2 expression in GC was significantly higher than that in cancer-adjacent tissues (<i>p</i> < 0.001), which was verified using real-time PCR, immunohistochemical staining and datasets from GEO. The 599 identified DEGs were primarily enriched in pathways related to tumorigenesis and tumor progression, including the focal adhesion pathway, signaling by vascular endothelial growth factor, and Wnt signaling. THBS2 expression was positively correlated with the enrichment of the macrophages (r = 0.590, <i>p</i> < 0.001), which was also confirmed by immunohistochemistry; however, negatively correlated with the enrichment of Th17 cells (r = 0.260, <i>p</i> < 0.001). The high expression of THBS2 was significantly correlated with the pathological grade (<i>p</i> < 0.01), histological grade (<i>p</i> < 0.05), histological type (<i>p</i> < 0.05), T stage (<i>p</i> < 0.001), and poor overall survival (OS) (<i>P =</i> 0.003) of GC. The constructed nomogram can well predict the 1-, 3-, and 5-years OS probability of patients with GC (C-index [95% confidence interval] = 0.725 [0.701-0.750]). <b>Conclusion:</b> THBS2 is closely related to the poor prognosis and immune infiltration of gastric cancer.',
                 'PMID': '35186032', 'DOI': '10.3389/fgene.2022.803460',
                 'Journal_Title': 'Frontiers in genetics',
                 'ISO_Abbreviation': 'Front Genet',
                 'Journal_Score': '2.41772151898734', 'ISSN': '1664-8021',
                 'ArticleDate': '2022-02-03',
                 'URL': 'https://pubmed.ncbi.nlm.nih.gov/35186032/', 'Level': 1},
             {
                 'Title': 'Blocking the TCA Cycle in Cancer Cells Potentiates CD36+ T-cell-Mediated Antitumor Immunity by Suppressing ER Stress-Associated THBS2 Signaling.',
                 'Abstract': 'The tricarboxylic acid (TCA) cycle is often rewired or dysregulated to meet the increased energy and biosynthetic demands of rapidly dividing cancer cells, and targeting the TCA cycle is a potential therapeutic strategy for treating cancer. However, tumor cell metabolism can impact other cells in the tumor microenvironment, and disrupting the TCA cycle in cancer cells could impact the antitumor immune response. In this study, using CPI-613 as a model drug for TCA cycle inhibition, we identified a molecular mechanism by which blocking the TCA cycle enhances T-cell-mediated antitumor immunity in the context of head and neck squamous cell carcinoma (HNSCC). Impairment of mitochondrial metabolism by CPI-613 induced endoplasmic reticulum stress in HNSCC cells, leading to increased expression of spliced X-box-binding protein 1. This, in turn, directly suppressed the transcriptional activity of the thrombospondin-2 gene. Correspondingly, CPI-613 reduced the secretion of thrombospondin-2 from HNSCC cells, enhancing the proliferation and cytotoxic potential of tumor-infiltrating CD36+CD8+ T cells by upregulating AKT-mTOR signaling. This mechanism ultimately enhanced antitumor immunity in a syngeneic mouse model of orthotopic HNSCC following CPI-613 treatment. These findings uncover the immunomodulatory role of the TCA cycle in cancer cells and suggest that targeting it is a promising approach to harness tumor-reactive immune cells. Significance: The immunomodulatory role of the TCA cycle in cancer cells provides a therapeutic opportunity to enhance antitumor immunity by targeting tumor cell metabolism.',
                 'PMID': '40293258', 'DOI': '10.1158/0008-5472.CAN-24-3477',
                 'Journal_Title': 'Cancer research',
                 'ISO_Abbreviation': 'Cancer Res', 'Journal_Score': '20.375',
                 'ISSN': '1538-7445', 'ArticleDate': '2025-06-02',
                 'URL': 'https://pubmed.ncbi.nlm.nih.gov/40293258/', 'Level': 1},
             {
                 'Title': 'Identification of the M2 Macrophage-associated Gene THBS2 as a Predictive Marker for Inflammatory Cancer Transformation.',
                 'Abstract': 'Ulcerative colitis (UC)-induced colitis-associated colorectal cancer (CAC) has a worse prognosis than sporadic colorectal cancer. And with the incidence of ulcerative colitis on the rise, it is critical to identify new therapeutic targets in time to stop the progression of inflammation to cancer. Through immunohistochemistry (IHC) and Gene Expression Omnibus (GEO) database analysis, we acquired the gene M2DEG, which is differentially expressed in M2 macrophages. The impact of M2DEG on the immune environment and clinical variables was confirmed through various data sets and actual tissue samples. Our findings indicate that patients with UC exhibiting reduced M2 macrophage infiltration tend to have more widespread disease, elevated endoscopic Mayo scores, and a higher probability of developing CAC. Through examining the string of M2DEG between UC and CAC, THBS2 emerged as a key marker. Elevated levels of THBS2 were notably linked to reduced overall survival (OS) and progression-free survival (RFS), and this heightened THBS2 expression played a crucial role in the spread of tumors, as verified by immunohistochemical studies. To sum up, patients with UC exhibiting reduced M2 macrophage infiltration have a higher propensity for CAC development, making THBS2 a crucial focus for converting UC into CAC. Furthermore, identifying antibody analogues targeting THBS2 could potentially lower the likelihood of CAC transformation in patients with UC.',
                 'PMID': '39045635', 'DOI': '10.1093/ibd/izae129',
                 'Journal_Title': 'Inflammatory bowel diseases',
                 'ISO_Abbreviation': 'Inflamm Bowel Dis', 'Journal_Score': '4.9',
                 'ISSN': '1536-4844', 'ArticleDate': '2025-04-10',
                 'URL': 'https://pubmed.ncbi.nlm.nih.gov/39045635/', 'Level': 1},
             {
                 'Title': 'Integrating bulk RNA-seq and scRNA-seq analyses revealed the function and clinical value of thrombospondins in colon cancer.',
                 'Abstract': 'Acting as mediators in cell-matrix and cell-cell communication, matricellular proteins play a crucial role in cancer progression. Thrombospondins (TSPs), a type of matricellular glycoproteins, are key regulators in cancer biology with multifaceted roles. Although TSPs have been implicated in anti-tumor immunity and epithelial-mesenchymal transition (EMT) in several malignancies, their specific roles to colon cancer remain elusive. Addressing this knowledge gap is essential, as understanding the function of TSPs in colon cancer could identify new therapeutic targets and prognostic markers.',
                 'PMID': '38827236', 'DOI': '10.1016/j.csbj.2024.05.021',
                 'Journal_Title': 'Computational and structural biotechnology journal',
                 'ISO_Abbreviation': 'Comput Struct Biotechnol J',
                 'Journal_Score': '3.06730769230769', 'ISSN': '2001-0370',
                 'ArticleDate': '2024-05-17',
                 'URL': 'https://pubmed.ncbi.nlm.nih.gov/38827236/',
                 'Level': 1}]}, {'biorxiv': [], 'medrxiv': [], 'pubmed': [{
        'Title': 'Cancer-associated fibroblast-derived gene signatures predict radiotherapeutic survival in prostate cancer patients.',
        'Abstract': 'Cancer-associated fibroblasts (CAFs) play multiple roles in regulating tumor metastasis and treatment response. Current clinical indicators are insufficient to accurately assess disease risk and radiotherapy response, emphasizing the urgent need for additional molecular prognostic markers.',
        'PMID': '36195908',
        'DOI': '10.1186/s12967-022-03656-5',
        'Journal_Title': 'Journal of translational medicine',
        'ISO_Abbreviation': 'J Transl Med',
        'Journal_Score': '8.125',
        'ISSN': '1479-5876',
        'ArticleDate': '2022-10-04',
        'URL': 'https://pubmed.ncbi.nlm.nih.gov/36195908/',
        'Level': 2},
        {
            'Title': 'XBP1 regulates the protumoral function of tumor-associated macrophages in human colorectal cancer.',
            'Abstract': 'Macrophages are among the most abundant immune cells in colorectal cancer (CRC). Re-educating tumor-associated macrophages (TAMs) to switch from protumoral to anti-tumoral activity is an attractive treatment strategy that warrants further investigation. However, little is known about the key pathway that is activated in TAMs. In this study, infitrating CD206<sup>+</sup> TAMs in CRC were sorted and subjected to RNA-seq analysis. Differentially expressed genes were found to be enriched in unfolded protein response/endoplasmic reticulum stress response processes, and XBP1 splicing/activation was specifically observed in TAMs. XBP1 activation in TAMs promoted the growth and metastasis of CRC. Ablation of XBP1 inhibited the expression of the pro-tumor cytokine signature of TAMs, including IL-6, VEGFA, and IL-4. Simultaneously, XBP1 depletion could directly inhibit the expression of SIRPα and THBS1, thereby blocking "don\'t eat me" recognition signals and enhancing phagocytosis. Therapeutic XBP1 gene editing using AAV2-sgXBP1 enhanced the anti-tumor activity. Together, XBP1 activation in TAMs drives CRC progression by elevating pro-tumor cytokine expression and secretion, as well as inhibiting macrophage phagocytosis. Targeting XBP1 signaling in TAMs may be a potential strategy for CRC therapy.',
            'PMID': '34667145',
            'DOI': '10.1038/s41392-021-00761-7',
            'Journal_Title': 'Signal transduction and targeted therapy',
            'ISO_Abbreviation': 'Signal Transduct Target Ther',
            'Journal_Score': '319.0',
            'ISSN': '2059-3635',
            'ArticleDate': '2021-10-20',
            'URL': 'https://pubmed.ncbi.nlm.nih.gov/34667145/',
            'Level': 2},
        {
            'Title': 'Systematic analysis of integrated bioinformatics to identify upregulated THBS2 expression in colorectal cancer cells inhibiting tumour immunity through the HIF1A/Lactic Acid/GPR132 pathway.',
            'Abstract': 'THBS2, a member of the extracellular matrix glycoprotein family, can effectively inhibit tumour growth and angiogenesis. This study aimed to investigate the biological role of THBS2 in various types of cancers and the mechanisms underlying the malignant progression of colorectal cancer (CRC).',
            'PMID': '37884956',
            'DOI': '10.1186/s12935-023-03103-5',
            'Journal_Title': 'Cancer cell international',
            'ISO_Abbreviation': 'Cancer Cell Int',
            'Journal_Score': '5.92727272727273',
            'ISSN': '1475-2867',
            'ArticleDate': '2023-10-27',
            'URL': 'https://pubmed.ncbi.nlm.nih.gov/37884956/',
            'Level': 1},
        {
            'Title': 'Integrating bulk RNA-seq and scRNA-seq analyses revealed the function and clinical value of thrombospondins in colon cancer.',
            'Abstract': 'Acting as mediators in cell-matrix and cell-cell communication, matricellular proteins play a crucial role in cancer progression. Thrombospondins (TSPs), a type of matricellular glycoproteins, are key regulators in cancer biology with multifaceted roles. Although TSPs have been implicated in anti-tumor immunity and epithelial-mesenchymal transition (EMT) in several malignancies, their specific roles to colon cancer remain elusive. Addressing this knowledge gap is essential, as understanding the function of TSPs in colon cancer could identify new therapeutic targets and prognostic markers.',
            'PMID': '38827236',
            'DOI': '10.1016/j.csbj.2024.05.021',
            'Journal_Title': 'Computational and structural biotechnology journal',
            'ISO_Abbreviation': 'Comput Struct Biotechnol J',
            'Journal_Score': '3.06730769230769',
            'ISSN': '2001-0370',
            'ArticleDate': '2024-05-17',
            'URL': 'https://pubmed.ncbi.nlm.nih.gov/38827236/',
            'Level': 1},
        {
            'Title': 'Bioinformatics analysis identifies COL1A1, THBS2 and SPP1 as potential predictors of patient prognosis and immunotherapy response in gastric cancer.',
            'Abstract': 'The present study aimed to use bioinformatics tools to explore pivotal genes associated with the occurrence of gastric cancer (GC) and assess their prognostic significance, and link with clinicopathological parameters. We also investigated the predictive role of COL1A1, THBS2, and SPP1 in immunotherapy.',
            'PMID': '33345281',
            'DOI': '10.1042/BSR20202564',
            'Journal_Title': 'Bioscience reports',
            'ISO_Abbreviation': 'Biosci Rep',
            'Journal_Score': '4.08974358974359',
            'ISSN': '1573-4935',
            'ArticleDate': '2021-01-29',
            'URL': 'https://pubmed.ncbi.nlm.nih.gov/33345281/',
            'Level': 1},
        {
            'Title': 'Thrombospondin-2 acts as a bridge between tumor extracellular matrix and immune infiltration in pancreatic and stomach adenocarcinomas: an integrative pan-cancer analysis.',
            'Abstract': 'Thrombospondin-2 (THBS2) is a versatile glycoprotein that regulates numerous biological functions, including the apoptosis-proliferation balance in endothelial cells, and it has been linked to tumor angiogenesis. However, the exact role of THBS2 in human cancer remains unknown. This study aimed to determine THBS2 expression in a pan-cancer analysis and its association with pan-cancer prognosis and to further identify its possible roles in tumor immunity and the extracellular matrix (ECM).',
            'PMID': '35701829',
            'DOI': '10.1186/s12935-022-02622-x',
            'Journal_Title': 'Cancer cell international',
            'ISO_Abbreviation': 'Cancer Cell Int',
            'Journal_Score': '5.92727272727273',
            'ISSN': '1475-2867',
            'ArticleDate': '2022-06-14',
            'URL': 'https://pubmed.ncbi.nlm.nih.gov/35701829/',
            'Level': 1},
        {
            'Title': 'The Construction and Comprehensive Analysis of ceRNA Networks and Tumor-Infiltrating Immune Cells in Bone Metastatic Melanoma.',
            'Abstract': '<b>Background/Aims:</b> As a malignant and melanocytic tumor, cutaneous melanoma is the devastating skin tumor with high rates of recurrence and metastasis. Bone is the common metastatic location, and bone metastasis may result in pathologic fracture, neurologic damage, and severe bone pain. Although metastatic melanoma was reported to get benefits from immunotherapy, molecular mechanisms and immune microenviroment underlying the melanoma bone metastasis and prognostic factors are still unknown. <b>Methods:</b> Gene expression profiling of 112 samples, including 104 primary melanomas and 8 bone metastatic melanomas from The Cancer Genome Atlas database, was assayed to construct a ceRNA network associated with bone metastases. Besides, we detected the fraction of 22 immune cell types in melanoma <i>via</i> the algorithm of "cell type identification by estimating relative subsets of RNA transcripts (CIBERSORT)." Based on the significant ceRNAs or immune cells, we constructed nomograms to predict the prognosis of patients with melanoma. Ultimately, correlation analysis was implemented to discover the relationship between the significant ceRNA and immune cells to reveal the potential signaling pathways. <b>Results:</b> We constructed a ceRNA network based on the interaction among 8 pairs of long noncoding RNA-microRNA and 15 pairs of microRNA-mRNA. CIBERSORT and ceRNA integration analysis discovered that AL118506.1 has both significant prognostic value (<i>P</i> = 0.002) and high correlation with T follicular helper cells (<i>P</i> = 0.033). Meanwhile, T cells CD8 and macrophages M2 were negatively correlated (<i>P</i> < 0.001). Moreover, we constructed two satisfactory nomograms (area under curve of 3-year survival: 0.899; 5-year survival: 0.885; and concordance index: 0.780) with significant ceRNAs or immune cells, to predict the prognosis of patients. <b>Conclusions:</b> In this study, we suggest that bone metastasis in melanoma might be related to AL118506.1 and its role in regulating thrombospondin 2 and T follicular helper cells. Two nomograms were constructed to predict the prognosis of patients with melanoma and demonstrated their value in improving the personalized management.',
            'PMID': '31608101',
            'DOI': '10.3389/fgene.2019.00828',
            'Journal_Title': 'Frontiers in genetics',
            'ISO_Abbreviation': 'Front Genet',
            'Journal_Score': '2.41772151898734',
            'ISSN': '1664-8021',
            'ArticleDate': '2019-09-25',
            'URL': 'https://pubmed.ncbi.nlm.nih.gov/31608101/',
            'Level': 2},
        {
            'Title': 'Five EMT-related genes signature predicts overall survival and immune environment in microsatellite instability-high gastric cancer.',
            'Abstract': 'Microsatellite instability-high (MSI-H) subgroup of gastric cancer (GC) is characterized by a high tumor mutational burden, increased lymphocytic infiltration, and enhanced inflammatory cytokines. GC patients with MSI-H status have a good response to immune checkpoint blockade management. However, heterogeneity within the subtype and the underlying mechanisms of shaping tumor microenvironments remain poorly understood.',
            'PMID': '35789544',
            'DOI': '10.1002/cam4.4975',
            'Journal_Title': 'Cancer medicine',
            'ISO_Abbreviation': 'Cancer Med',
            'Journal_Score': '2.31205673758865',
            'ISSN': '2045-7634',
            'ArticleDate': '2022-07-04',
            'URL': 'https://pubmed.ncbi.nlm.nih.gov/35789544/',
            'Level': 2},
        {
            'Title': 'Whole-transcriptome defines novel glucose metabolic subtypes in colorectal cancer.',
            'Abstract': 'Colorectal cancer (CRC) is the most prevalent malignancy of the digestive system. Glucose metabolism plays a crucial role in CRC development. However, the heterogeneity of glucose metabolic patterns in CRC is not well characterized. Here, we classified CRC into specific glucose metabolic subtypes and identified the key regulators. 2228 carbohydrate metabolism-related genes were screened out from the GeneCards database, 202 of them were identified as prognosis genes in the TCGA database. Based on the expression patterns of the 202 genes, three metabolic subtypes were obtained by the non-negative matrix factorization clustering method. The C1 subtype had the worst survival outcome and was characterized with higher immune cell infiltration and more activation in extracellular matrix pathways than the other two subtypes. The C2 subtype was the most prevalent in CRC and was characterized by low immune cell infiltration. The C3 subtype had the smallest number of individuals and had a better prognosis, with higher levels of NRF2 and TP53 pathway expression. Secreted frizzled-related protein 2 (SFRP2) and thrombospondin-2 (THBS2) were confirmed as biomarkers for the C1 subtype. Their expression levels were elevated in high glucose condition, while their knockdown inhibited migration and invasion of HCT 116 cells. The analysis of therapeutic potential found that the C1 subtype was more sensitive to immune and PI3K-Akt pathway inhibitors than the other subtypes. To sum up, this study revealed a novel glucose-related CRC subtype, characterized by SFRP2 and THBS2, with poor prognosis but possible therapeutic benefits from immune and targeted therapies.',
            'PMID': '38116696',
            'DOI': '10.1111/jcmm.18065',
            'Journal_Title': 'Journal of cellular and molecular medicine',
            'ISO_Abbreviation': 'J Cell Mol Med',
            'Journal_Score': '3.48214285714286',
            'ISSN': '1582-4934',
            'ArticleDate': '2023-12-20',
            'URL': 'https://pubmed.ncbi.nlm.nih.gov/38116696/',
            'Level': 2},
        {
            'Title': 'Thrombospondin 1, thrombospondin 2 and the eye.',
            'Abstract': 'Thrombospondin 1 and thrombospondin 2 (TSP1 and TSP2), which comprise the subgroup A thrombospondins, are matricellular proteins. As matricellular proteins, they modulate interactions between cells and the cellular environment, regulate cell adhesion and typically are expressed during tissue formative processes. In general, TSP1 and TSP2 counter angiogenesis (including tumour angiogenesis) and play important but contrasting roles during cutaneous repair. The two proteins are involved in development, including that of the eye, although evidence suggests that they have their greatest impact during tissue production in the adult. In the normal adult eye, they tend to be found at sites of ongoing matrix synthesis or cell-matrix interactions. At these sites, the two proteins possibly influence cellular differentiation and/or basement membrane deposition. TSP1 is also present in the intraocular fluids and drainage pathway, where it may function in maintaining the anti-angiogenic environment and in intraocular pressure control, respectively. TSP1 could also be involved in ocular immune privilege. Unlike in skin wounds, where TSP1 is derived from the blood and is present only in the early phases of repair, ocular tissue damage appears to lead to protacted TSP1 synthesis by local cells. This response might help suppress angiogenesis in the transparent tissues of the eye and so lessen visual axis opacification following injury. However, TSP2, which is also produced by damaged ophthalmic tissue and may be especially important in matrix organisation, seems to augment contraction in anomalous intraocular fibrosis. Elucidating the roles of TSP1 and TSP2 in ocular physiology and pathobiology may lead to improved therapies for neovascular, neoplastic, reparative and other ophthalmic diseases.',
            'PMID': '15996506',
            'DOI': None,
            'Journal_Title': 'Progress in retinal and eye research',
            'ISO_Abbreviation': 'Prog Retin Eye Res',
            'Journal_Score': 'None',
            'ISSN': '1350-9462',
            'ArticleDate': '2005-06-29',
            'URL': 'https://pubmed.ncbi.nlm.nih.gov/15996506/',
            'Level': 2}]},
         {'biorxiv': [], 'medrxiv': [], 'pubmed': [{
             'Title': 'Bioinformatics analysis identifies COL1A1, THBS2 and SPP1 as potential predictors of patient prognosis and immunotherapy response in gastric cancer.',
             'Abstract': 'The present study aimed to use bioinformatics tools to explore pivotal genes associated with the occurrence of gastric cancer (GC) and assess their prognostic significance, and link with clinicopathological parameters. We also investigated the predictive role of COL1A1, THBS2, and SPP1 in immunotherapy.',
             'PMID': '33345281', 'DOI': '10.1042/BSR20202564',
             'Journal_Title': 'Bioscience reports',
             'ISO_Abbreviation': 'Biosci Rep',
             'Journal_Score': '4.08974358974359', 'ISSN': '1573-4935',
             'ArticleDate': '2021-01-29',
             'URL': 'https://pubmed.ncbi.nlm.nih.gov/33345281/', 'Level': 1},
             {
                 'Title': 'Thrombospondin-2 acts as a bridge between tumor extracellular matrix and immune infiltration in pancreatic and stomach adenocarcinomas: an integrative pan-cancer analysis.',
                 'Abstract': 'Thrombospondin-2 (THBS2) is a versatile glycoprotein that regulates numerous biological functions, including the apoptosis-proliferation balance in endothelial cells, and it has been linked to tumor angiogenesis. However, the exact role of THBS2 in human cancer remains unknown. This study aimed to determine THBS2 expression in a pan-cancer analysis and its association with pan-cancer prognosis and to further identify its possible roles in tumor immunity and the extracellular matrix (ECM).',
                 'PMID': '35701829', 'DOI': '10.1186/s12935-022-02622-x',
                 'Journal_Title': 'Cancer cell international',
                 'ISO_Abbreviation': 'Cancer Cell Int',
                 'Journal_Score': '5.92727272727273', 'ISSN': '1475-2867',
                 'ArticleDate': '2022-06-14',
                 'URL': 'https://pubmed.ncbi.nlm.nih.gov/35701829/', 'Level': 1},
             {
                 'Title': 'Identification of a basement membrane gene signature for predicting prognosis and estimating the tumor immune microenvironment in prostate cancer.',
                 'Abstract': 'Basement membrane plays an important role in tumor invasion and metastasis, which is closely related to prognosis. However, the prognostic value and biology of basement membrane genes (BMGs) in prostate cancer (PCa) remain unknown. In the TCGA training set, we used differentially expressed gene analysis, protein-protein interaction networks, univariate and multivariate Cox regression, and least absolute shrinkage and selection operator regression to construct a basement membrane-related risk model (BMRM) and validated its effectiveness in the MSKCC validation set. Furthermore, the accurate nomogram was constructed to improve clinical applicability. Patients with PCa were divided into high-risk and low-risk groups according to the optimal cut-off value of the basement membrane-related risk score (BMRS). It was found that BMRS was significantly associated with RFS, T-stage, Gleason score, and tumor microenvironmental characteristics in PCa patients. Further analysis showed that the model grouping was closely related to tumor immune microenvironment characteristics, immune checkpoint inhibitors, and chemotherapeutic drug sensitivity. In this study, we developed a new BMGs-based prognostic model to determine the prognostic value of BMGs in PCa. Finally, we confirmed that THBS2, a key gene in BMRM, may be an important link in the occurrence and progression of PCa. This study provides a novel perspective to assess the prognosis of PCa patients and provides clues for the selection of future personalized treatment regimens.',
                 'PMID': '38240702', 'DOI': '10.18632/aging.205445',
                 'Journal_Title': 'Aging',
                 'ISO_Abbreviation': 'Aging (Albany NY)', 'Journal_Score': 'None',
                 'ISSN': '1945-4589', 'ArticleDate': '2024-01-17',
                 'URL': 'https://pubmed.ncbi.nlm.nih.gov/38240702/',
                 'Level': 1}]}, {'biorxiv': [], 'medrxiv': [], 'pubmed': [{
        'Title': 'CAF-macrophage crosstalk in tumour microenvironments governs the response to immune checkpoint blockade in gastric cancer peritoneal metastases.',
        'Abstract': 'Peritoneal metastasis is the most common metastasis pattern of gastric cancer. Patients with gastric cancer peritoneal metastasis (GCPM) have a poor prognosis and respond poorly to conventional treatments. Recently, immune checkpoint blockade (ICB) has demonstrated favourable efficacy in the treatment of GCPM. Stratification of best responders and elucidation of resistance mechanisms of ICB therapies are highly important and remain major clinical challenges.',
        'PMID': '39537239',
        'DOI': '10.1136/gutjnl-2024-333617',
        'Journal_Title': 'Gut',
        'ISO_Abbreviation': 'Gut',
        'Journal_Score': '36.75',
        'ISSN': '1468-3288',
        'ArticleDate': '2025-02-06',
        'URL': 'https://pubmed.ncbi.nlm.nih.gov/39537239/',
        'Level': 2},
        {
            'Title': 'Systematic analysis of integrated bioinformatics to identify upregulated THBS2 expression in colorectal cancer cells inhibiting tumour immunity through the HIF1A/Lactic Acid/GPR132 pathway.',
            'Abstract': 'THBS2, a member of the extracellular matrix glycoprotein family, can effectively inhibit tumour growth and angiogenesis. This study aimed to investigate the biological role of THBS2 in various types of cancers and the mechanisms underlying the malignant progression of colorectal cancer (CRC).',
            'PMID': '37884956',
            'DOI': '10.1186/s12935-023-03103-5',
            'Journal_Title': 'Cancer cell international',
            'ISO_Abbreviation': 'Cancer Cell Int',
            'Journal_Score': '5.92727272727273',
            'ISSN': '1475-2867',
            'ArticleDate': '2023-10-27',
            'URL': 'https://pubmed.ncbi.nlm.nih.gov/37884956/',
            'Level': 1},
        {
            'Title': 'Bioinformatics analysis identifies COL1A1, THBS2 and SPP1 as potential predictors of patient prognosis and immunotherapy response in gastric cancer.',
            'Abstract': 'The present study aimed to use bioinformatics tools to explore pivotal genes associated with the occurrence of gastric cancer (GC) and assess their prognostic significance, and link with clinicopathological parameters. We also investigated the predictive role of COL1A1, THBS2, and SPP1 in immunotherapy.',
            'PMID': '33345281',
            'DOI': '10.1042/BSR20202564',
            'Journal_Title': 'Bioscience reports',
            'ISO_Abbreviation': 'Biosci Rep',
            'Journal_Score': '4.08974358974359',
            'ISSN': '1573-4935',
            'ArticleDate': '2021-01-29',
            'URL': 'https://pubmed.ncbi.nlm.nih.gov/33345281/',
            'Level': 1},
        {
            'Title': 'Characterization of butyrate-metabolism in colorectal cancer to guide clinical treatment.',
            'Abstract': "Colorectal cancer (CRC) is the third most prevalent one in the world among the most common malignant tumors. Numerous studies have shown that butyrate has demonstrated promise as an antitumor agent in a variety of human cancer types. However, butyrate remains understudied in CRC tumorigenesis and progression. In this study, we explored therapeutic strategies to treat CRC by examining the role of butyrate metabolism. First, from the Molecular Signature Database (MSigDB), we identified 348 butyrate metabolism-related genes (BMRGs). Next, we downloaded 473 CRC and 41 standard colorectal tissue samples from The Cancer Genome Atlas (TCGA) database and the transcriptome data of GSE39582 dataset from Gene Expression Omnibus (GEO) database. Then we evaluated the expression patterns of butyrate metabolism-related genes with difference analysis in CRC. Through univariate Cox regression and least absolute shrinkage and selection operator (LASSO) analysis, a prognostic model was constructed based on differentially expressed BMRGs. In addition, we discovered an independent prognostic marker for CRC patients. According to the expression levels and coefficients of identified BMRGs, the risk scores of all CRC samples were calculated. Utilizing differentially expressed genes in the high- and low-risk groups, we also constructed a Protein-Protein Interaction (PPI) network to visualize the interactions between proteins. Through the results of PPI network, we screened out differentially expressed target butyrate metabolism-related genes from ten hub genes. Finally, we performed clinical correlation analysis, immune cell infiltration analysis, and mutation analysis for these target genes. One hundred and seventy three differentially expressed butyrate metabolism-related genes were screened out in all the CRC samples. The prognostic model was established with univariate Cox regression and LASSO regression analysis. CRC patients' overall survival was significantly lower in the high-risk group than in the low-risk group for both training and validation set. Among the ten hub genes identified from the PPI network, four target butyrate metabolism-related genes were identified containing FN1, SERPINE1, THBS2, and COMP, which might provide novel markers or targets for treating CRC patients. Eighteen butyrate metabolism-related genes were used to develop a risk prognostic model that could be helpful for doctors to predict CRC patients' survival rate. Using this model, it is beneficial to forecast the response of CRC patients to immunotherapy and chemotherapy, thus making it easier to custom tailor cancer chemotherapy and immunotherapy to the individual patient.",
            'PMID': '36991138',
            'DOI': '10.1038/s41598-023-32457-z',
            'Journal_Title': 'Scientific reports',
            'ISO_Abbreviation': 'Sci Rep',
            'Journal_Score': '5.4',
            'ISSN': '2045-2322',
            'ArticleDate': '2023-03-29',
            'URL': 'https://pubmed.ncbi.nlm.nih.gov/36991138/',
            'Level': 2},
        {
            'Title': 'Identification of Key Genes Associated with Tumor Microenvironment Infiltration and Survival in Gastric Adenocarcinoma via Bioinformatics Analysis.',
            'Abstract': 'Gastric carcinoma (GC) is the fifth most commonly diagnosed cancer and the third leading cause of cancer-related deaths globally. The tumor microenvironment plays a significant role in the pathogenesis, prognosis, and response to immunotherapy. However, the immune-related molecular mechanisms underlying GC remain elusive. Bioinformatics analysis of the gene expression of GC and paracancerous healthy tissues from the same patient was performed to identify the key genes and signaling pathways, as well as their correlation to the infiltration of the tumor microenvironment (TME) by various immune cells related to GC development.',
            'PMID': '38610959',
            'DOI': '10.3390/cancers16071280',
            'Journal_Title': 'Cancers',
            'ISO_Abbreviation': 'Cancers (Basel)',
            'Journal_Score': '3.83529411764706',
            'ISSN': '2072-6694',
            'ArticleDate': '2024-03-26',
            'URL': 'https://pubmed.ncbi.nlm.nih.gov/38610959/',
            'Level': 2},
        {
            'Title': 'Revealing Potential Therapeutic Targets in Gastric Cancer through Inflammation and Protein-Protein Interaction Hub Networks.',
            'Abstract': '<b>Background:</b> Gastric cancer (GC) ranks second in incidence and mortality among digestive system cancer, following colorectal cancer. Currently treatment options are limited, and the prognosis for GC remains poor. <b>Methods:</b> Four bulk RNA sequencing (RNA-seq) datasets and two single-cell RNA sequencing (scRNA-seq) datasets were downloaded from the Gene Expression Omnibus (GEO) database. Initially, we identified differentially expressed genes (DEGs). The intersection list of inflammatory response-related DEGs (IRR-DEGs) was utilized for enrichment analyses. Hub genes were extracted from the protein-protein interaction (PPI) network of DEGs, exploring their expression in the context of scRNA-seq landscapes and cell-cell communication. IRR hub DEGs were identified, and pathway and receptor-ligand pairs were analyzed at this gene level. <b>Results:</b> The analysis identified 69 DEGs in GC. Among these, 8 IRR-DEGs (SPP1, TIMP1, SERPINF1, TNFAIP6, LGALS1, LY6E, MSR1, and SELE) were closely associated with 19 types of immune cells and various lymphocytes. Of the 12 hub genes (SPP1, TIMP1, FSTL1, THY1, COL4A1, FBN1, ASPN, COL10A1, COL5A1, THBS2, LUM, and SPARC), their expression is significantly enhanced in stem cells, primarily involving communication with monocytes, and four prognostic-related genes were discovered. Two IRR hub DEGs indicated that the SPP1 signaling pathway, specifically the SPP1-CD44 ligand-receptor pairs, plays a critical role. <b>Conclusion:</b> We have collectively identified 18 genes that could serve as biomarkers for future GC targeting. The discovery of the SPP1-CD44 ligand-receptor axis not only elucidates a novel inflammatory signaling pathway driving tumor progression, but also provides a potential therapeutic target for disrupting cancer-stromal interactions. Importantly, these biomarkers lay the foundation for developing precision immunotherapies that target the inflammatory-immune axis in GC management.',
            'PMID': '40535808',
            'DOI': '10.7150/jca.112218',
            'Journal_Title': 'Journal of Cancer',
            'ISO_Abbreviation': 'J Cancer',
            'Journal_Score': '2.52713178294574',
            'ISSN': '1837-9664',
            'ArticleDate': '2025-06-12',
            'URL': 'https://pubmed.ncbi.nlm.nih.gov/40535808/',
            'Level': 2}]},
         {'biorxiv': [], 'medrxiv': [], 'pubmed': [{
             'Title': 'Multi-scale integrative analyses identify THBS2<sup>+</sup> cancer-associated fibroblasts as a key orchestrator promoting aggressiveness in early-stage lung adenocarcinoma.',
             'Abstract': '<b>Rationale:</b> Subsets of patients with early-stage lung adenocarcinoma (LUAD) have a poor post-surgical course after curative surgery. However, biomarkers stratifying this high-risk subset and molecular underpinnings underlying the aggressive phenotype remain unclear. <b>Methods:</b> We integrated bulk and single-cell transcriptomics, proteomics, secretome and spatial profiling of clinical early-stage LUAD samples to identify molecular underpinnings that promote the aggressive phenotype. <b>Results:</b> We identified and validated THBS2, at multi-omic levels, as a tumor size-independent biomarker that robustly predicted post-surgical survival in multiple independent clinical cohorts of early-stage LUAD. Furthermore, scRNA-seq data revealed that THBS2 is exclusively derived from a specific cancer-associated fibroblast (CAF) subset that is distinct from CAFs defined by classical markers. Interestingly, our data demonstrated that THBS2 was preferentially secreted via exosomes in early-stage LUAD tumors with high aggressiveness, and its levels in the peripheral plasma associated with short recurrence-free survival. Further characterization showed that THBS2-high early-stage LUAD was characterized by suppressed antitumor immunity. Specifically, beyond tumor cells, THBS2+ CAFs mainly interact with B and CD8+ T lymphocytes as well as macrophages within tumor microenvironment of early-stage LUAD, and THBS2-high LUAD was associated with decreased immune cell infiltrates but increased immune exhaustion marker. Clinically, high THBS2 expression predicted poor response to immunotherapies and short post-treatment survival of patients. Finally, THBS2 recombinant protein suppressed <i>ex vivo</i> T cells proliferation and promoted <i>in vivo</i> LUAD tumor growth and distant micro-metastasis. <b>Conclusions:</b> Our multi-level analyses uncovered tumor-specific THBS2+ CAFs as a key orchestrator promoting aggressiveness in early-stage LUAD.',
             'PMID': '35547750', 'DOI': '10.7150/thno.69590',
             'Journal_Title': 'Theranostics',
             'ISO_Abbreviation': 'Theranostics',
             'Journal_Score': '27.8571428571429', 'ISSN': '1838-7640',
             'ArticleDate': '2022-03-28',
             'URL': 'https://pubmed.ncbi.nlm.nih.gov/35547750/', 'Level': 1},
             {
                 'Title': 'Serum protein risk stratification score for diagnostic evaluation of metabolic dysfunction-associated steatohepatitis.',
                 'Abstract': 'Reliable, noninvasive tools to diagnose at-risk metabolic dysfunction-associated steatohepatitis (MASH) are urgently needed to improve management. We developed a risk stratification score incorporating proteomics-derived serum markers with clinical variables to identify high-risk patients with MASH (NAFLD activity score >4 and fibrosis score >2).',
                 'PMID': '39621304', 'DOI': '10.1097/HC9.0000000000000586',
                 'Journal_Title': 'Hepatology communications',
                 'ISO_Abbreviation': 'Hepatol Commun',
                 'Journal_Score': '5.44444444444444', 'ISSN': '2471-254X',
                 'ArticleDate': '2024-11-29',
                 'URL': 'https://pubmed.ncbi.nlm.nih.gov/39621304/', 'Level': 2},
             {
                 'Title': 'TGF-β Score based on <i>Silico</i> Analysis can Robustly Predict Prognosis and Immunological Characteristics in Lower-grade Glioma: The Evidence from Multicenter Studies.',
                 'Abstract': 'Nowadays, mounting evidence shows that variations in TGF-β signaling pathway-related components influence tumor development. Current research has patents describing the use of anti-TGF-β antibodies and checkpoint inhibitors for the treatment of proliferative diseases. Importantly, TGF-β signaling pathway is significant for lower-grade glioma (LGG) to evade host immunity. Loss of particular tumor antigens and shutdown of professional antigenpresenting cell activity may render the anti-tumor response ineffective in LGG patients. However, the prognostic significance of TGF-β related genes in LGG is still unknown.',
                 'PMID': '37718518', 'DOI': '10.2174/1574892819666230915143632',
                 'Journal_Title': 'Recent patents on anti-cancer drug discovery',
                 'ISO_Abbreviation': 'Recent Pat Anticancer Drug Discov',
                 'Journal_Score': '4.45569620253165', 'ISSN': '2212-3970',
                 'ArticleDate': '',
                 'URL': 'https://pubmed.ncbi.nlm.nih.gov/37718518/', 'Level': 2},
             {
                 'Title': 'Proteomic analysis of exosomes isolated from human malignant pleural effusions.',
                 'Abstract': 'Exosomes are membrane vesicles from endosomal origin secreted by various cells such as hematopoietic, epithelial, and tumor cells. Exosomes secreted by tumor cells contain specific antigens potentially useful for immunotherapeutic purposes. Our aim was to determine if exosomes are present in human cancerous pleural effusions and to identify their proteomic content. Exosomes were purified by sucrose gradient ultracentrifugation, and electron microscopy was used to check both concentration and purity of exosomes. Proteins were separated by one-dimensional sodium dodecyl sulfate-polyacrylamide gel electrophoresis, and protein bands were identified by matrix-assisted laser desorption ionization time-of-flight mass spectrometry and Western blotting. Exosomes were present in pleural fluid obtained from patients suffering from mesothelioma (n = 4), lung cancer (n = 2), breast cancer (n = 2), and ovarian cancer (n = 1). As previously reported by others, antigen-presenting molecules, cytoskeletal proteins, and signal transduction-involved proteins were present. Proteins not previously reported were identified (SNX25, BTG1, PEDF, thrombospondin 2). Different types of immunoglobulins and complement factors were abundantly present in the sucrose fractions containing exosomes. Exosome-directed specificity of these immunoglobulins was not observed. In conclusion, sucrose gradient ultracentrifugation allows isolation of exosomes from malignant pleural effusions. However, pleural fluid proteins and especially immunoglobulins are coisolated and may hamper the use of exosomes isolated from malignant effusion for immunotherapy programs.',
                 'PMID': '14975938', 'DOI': None,
                 'Journal_Title': 'American journal of respiratory cell and molecular biology',
                 'ISO_Abbreviation': 'Am J Respir Cell Mol Biol',
                 'Journal_Score': 'None', 'ISSN': '1044-1549',
                 'ArticleDate': '2004-02-19',
                 'URL': 'https://pubmed.ncbi.nlm.nih.gov/14975938/',
                 'Level': 2}]}]
